# Generated by Django 4.2.5 on 2023-09-27 02:01

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[], max_length=10)),
                ('operater', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booth_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, editable=False, max_length=10)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='Booth_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boothimages', to='booth.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
