# Generated by Django 4.2.5 on 2023-09-30 05:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.booth_image_upload_path),
        ),
    ]
