# Generated by Django 4.2.5 on 2023-09-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="location",
            field=models.CharField(
                choices=[
                    ("사회과학관", "사회과학관"),
                    ("혜화관", "혜화관"),
                    ("팔정도", "팔정도"),
                    ("원흥관", "원흥관"),
                    ("만해광장", "만해광장"),
                    ("학생회관", "학생회관"),
                    ("학림관", "학림관"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booth",
            name="type",
            field=models.CharField(
                choices=[("주간부스", "주간부스"), ("야간부스", "야간부스")], max_length=10
            ),
        ),
    ]
