# Generated by Django 4.2.5 on 2023-10-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="type",
            field=models.CharField(
                choices=[("주간부스", "주간부스"), ("야간부스", "야간부스"), ("기타부스", "기타부스")],
                max_length=10,
            ),
        ),
    ]
