# Generated by Django 4.2.5 on 2023-09-30 06:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_alter_booth_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path),
        ),
    ]
