# Generated by Django 4.2.5 on 2023-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0002_alter_booth_location_alter_booth_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="insta_url",
            field=models.URLField(default="https://www.instagram.com/your_username/"),
        ),
    ]
