# Generated by Django 4.2.5 on 2023-10-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0004_alter_booth_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="type",
            field=models.CharField(
                choices=[
                    ("주간부스", "주간부스"),
                    ("야간부스", "야간부스"),
                    ("플리마켓", "플리마켓"),
                    ("푸드트럭", "푸드트럭"),
                ],
                max_length=10,
            ),
        ),
    ]
