# Generated by Django 4.2.5 on 2023-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_alter_booth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booth',
            name='insta_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
