# Generated by Django 4.2.5 on 2023-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, editable=False, max_length=10)),
            ],
        ),
    ]
