# Generated by Django 4.2.5 on 2023-10-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('icon', models.CharField(choices=[('cry', 'cry'), ('hip', 'hip'), ('festival', 'festival'), ('fire', 'fire'), ('heart', 'heart')], default='cry', max_length=10)),
                ('key', models.CharField(blank=True, editable=False, max_length=10)),
            ],
        ),
    ]
