# Generated by Django 4.2.5 on 2023-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
