# Generated by Django 4.2.5 on 2023-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_abused',
            field=models.BooleanField(default=False),
        ),
    ]
