# Generated by Django 4.2.5 on 2023-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='icon',
            field=models.CharField(choices=[('cry', 'cry'), ('hip', 'hip'), ('festival', 'festival'), ('fire', 'fire'), ('heart', 'heart')], default='cry', max_length=10),
        ),
    ]
