# Generated by Django 4.2.5 on 2023-10-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_is_abused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
