# Generated by Django 4.2.5 on 2023-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='icon',
            field=models.CharField(choices=[('hip', 'hip'), ('festival', 'festival'), ('fire', 'fire'), ('heart', 'heart'), ('haapy', 'haapy'), ('best', 'best'), ('cry', 'cry')], default='festival', max_length=10),
        ),
    ]
