# Generated by Django 4.2.5 on 2023-09-30 05:33

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('축제', '축제'), ('기타', '기타')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('동아리', '동아리'), ('학과', '학과')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=notice.models.promotion_image_upload_path)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotionimages', to='notice.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=notice.models.notification_image_upload_path)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationimages', to='notice.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
