# Generated by Django 4.2.5 on 2023-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
