# Generated by Django 4.2.5 on 2023-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_promotion_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_thumbnails/'),
        ),
    ]
