# Generated by Django 4.2.5 on 2023-09-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_remove_promotion_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
