# Generated by Django 4.2.5 on 2023-09-29 05:17

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_remove_promotion_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=notice.models.notification_image_upload_path),
        ),
        migrations.AlterField(
            model_name='promotion_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=notice.models.promotion_image_upload_path),
        ),
    ]
